################################################################
###                HeavenChat by RFSMassacre                 ###
###                                                          ###
###   Discord Contact: RFSMassacre#8365                      ###
###                                                          ###
### Feel free to contact me for support, but be curtous and  ###
### don't freak out and scream vaguely like I'm some Trump   ###
### supporter. :[                                            ###
###                                                          ###
################################################################

enable-join-messages: true
enable-chat-logging: true

#Default channel every new player auto-focuses to
default-channel: "global"

#Settings for auto-focusing channels when switching servers
force-focus-channels: true
ignored-channels:
    - "staff"

#Range of local channels
local-range: 128

#Sound of ping (Use 1.8 names so it can be compatible with all versions.)
ping:
    enabled: true
    sound: "ITEM_PICKUP"
    volume: 1.0
    pitch: 0.4
    
highlight:
    color: "&e"
    mention: true
    keywords:
        - "help"
        - "staff"
      
rank-colors:
    - "owner &e"
    - "admin &c"
    - "mod &b"
    - "helper &a"

commands:
    - "ban"
    - "kick"
    - "mute"
    - "warn"
    - "kick"
    - "op"
    - "deop"

servers:
    Discord: 
        prefix: "&1[&9Discord&1] "
        color: "&6"
        channel: "global"
    Hub: 
        prefix: "&6[&eHub&6] "
        color: "&e"
        channel: "global"
    Registry: 
        prefix: "&8[&7Registry&8] "
        color: "&7"
        channel: "server"
    Survival: 
        prefix: "&2[&aSurvival&2] "
        color: "&2"
        channel: "server"
    Creative: 
        prefix: "&3[&bCreative&3] "
        color: "&3"
        channel: "server"
    KitPVP: 
        prefix: "&4[&cKitPVP&4] "
        color: "&4"
        channel: "server"
    Skyblock: 
        prefix: "&5[&dSkyblock&5] "
        color: "&5"
        channel: "server"
    
pm-formats:
    pm-send: "&6You &2&l» &f{receiver}&r &5&l> &d{message}"
    pm-receive: "&f{sender}&r &c&l» &6You &5&l> &d{message}"
    pm-spy: "&f{sender}&r &7&l» &f{receiver}&r &8&l> &7{message}"
    
list-format:
    no-staff-online: "&cNo staff is currently online."
    no-players-online: "&cNone currently "
    
nicknames:
    prefix: "&f●"
    min-length: 3
    max-length: 16
    
display-name: "{prefix}{suffix}{name}"
    
#In Minutes
afk:
    timeout: 15
    cooldown: 10
    
threads:
    afk:
        delay: 1
        interval: 1
    channel:
        delay: 1
        interval: 1

filters:
    profanity-filter: 
        enabled: true
        #Out of 100
        block-percent: 70
        censor: '*'
    flood-filter:
        enabled: true
        #In seconds
        message-cooldown: 3
        #In minutes
        afk-cooldown: 10
    repitition-filter:
        enabled: true
        #Out of 100
        block-percent: 80
    character-filter:
        enabled: true
    word-length-filter:
        enable: true
        limit: 16
    caps-filter:
        enabled: true
        limit: 6
    ip-filter:
        enabled: true
        replace: "<IP blocked>"
    domain-filter:
        enabled: true
        replace: "<domain blocked>"
        
blocked-words:
    - arsehole
    - asshole
    - fuck
    - shit
    - bitch
    - piss
    - pussy
    - cock
    - dick
    - cum
    - cunt
    - jizz
    - blowjob
    - rimjob
    - wanker
    - douche
    - tits
    - titties
    - nigger
    - nigga
    - chode
    - whore
    - slut
    - skank
    - bastard
    - buttplug
    - dildo
    - chink
    - spick
    - damn
    - dammit
    - fag
    - dike
    - dyke
    - handjob
    - sex
    - thot
    - jackass
    - lezbo
    - nutsack
    - prick
    - queef
    - twat
    - horny
    - jackoff
    - wank
    - retard
    